version: '2.0'
services:

  application:
    hostname: dev.somedomain.com.br
    container_name: CONTAINER_NAME
    build:
      context: .
    volumes:
      - ./:/var/www/html
      - ./docker/logs/nginx:/var/log/nginx
      - ./docker/logs/php7:/var/log/php7
    ports:
      - "80:8000"
      - "443:443"
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.2
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - database-data:/var/lib/mysql

volumes:
  database-data:
    driver: "local"