version: '2.0'
services:

  application:
    build:
      context: .
    volumes:
      - ./:/var/www/html
      - ./docker/logs/nginx:/var/log/nginx
      - ./docker/logs/php7:/var/log/php7
    ports:
      - "80:8000"
      - "443:443"
    depends_on:
      - database

  database:
    image: mariadb:10.2
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - "33306:3306"
    volumes:
      - database-data:/var/lib/mysql

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

volumes:
  database-data:
    driver: "local"
  redis-data:
    driver: "local"